
robot_radius: 0.1
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0
#footprint: [[-0.2,-0.2],[-0.2,0.2], [0.2, 0.2], [0.2,-0.2]]

#cost_scaling_factor: 10.0
obstacles_laser:
  observation_sources: laser_scan_sensor
  laser_scan_sensor: { data_type: LaserScan, topic: scan, marking: true, clearing: true, inf_is_valid: true}
inflation:
    inflation_radius: 0.1

