#global_frame: map
robot_base_frame: base_link
#update_frequency: 5.0
#publish_frequency: 2.0
rolling_window: true
static_map: false
track_unknown_space: false
#width: 5.0
#height: 5.0
#resolution: 0.02
#tranform_tolerance: 0.5
#planner_frequency: 1.0
#planner_patiente: 5.0
plugins:
  - {name: obstacles_laser, type: "costmap_2d::ObstacleLayer"}
  - {name: inflation, type: "costmap_2d::InflationLayer"}
